version: '3.8'

services:
  nq-core:
    container_name: nq-core
    image: 516240037474.dkr.ecr.us-east-1.amazonaws.com/core:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING.DATASOURCE.URL=jdbc:mysql://nq-database.cdhhh9aecm7w.us-east-1.rds.amazonaws.com:3306/core
    networks:
      - bridge_network

networks:
  bridge_network:
    driver: bridge